lst=[]
i=0
while(i<5):
    inp=int(input("enter your value"))
    lst.append(inp)
    tpl=tuple(lst)
    i+=1
print(tpl)
lst1=[]
i=0
while(i<len(tpl)):
    a=tpl[i]
    lst1.append(a)
    tpl1=tuple(lst1)
    i=i+2
print(tpl1)
lst2=[]
i=1
while(i<len(tpl)):
    b=tpl[i]
    lst2.append(b)
    tpl2=tuple(lst2)
    i=i+2
print(tpl2)
